# SPDX-License-Identifier: SHL-0.51
+define+TRANSDOT_ENABLE+SIMULATION
+define+USE_TRANSDOT_MULTIPLIER
+define+USE_TRANSDOT_EXPONENT_DATAPATH
+define+USE_TRANSDOT_ADDEND_DATAPATH
//+define+COMBINATIONAL
+define+USE_TRANSDOT_NORMALIZE_DATAPATH
+define+FP4_INCLUDED
//+define+FP8_INCLUDED
+incdir+${FPNEW_HOME}/src/common_cells/include
+incdir+${FPNEW_HOME}/src
+incdir+${FPNEW_HOME}/src/common_cells/src
${FPNEW_HOME}/src/fpnew_pkg.sv
${FPNEW_HOME}/src/fpnew_cast_multi.sv
${FPNEW_HOME}/src/fpnew_classifier.sv
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v
${FPNEW_HOME}/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v
${FPNEW_HOME}/vendor/openc910/C910_RTL_FACTORY/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v
${FPNEW_HOME}/src/fpnew_divsqrt_th_32.sv
${FPNEW_HOME}/src/fpnew_divsqrt_th_64_multi.sv
${FPNEW_HOME}/src/fpnew_divsqrt_multi.sv
${FPNEW_HOME}/src/fpnew_fma.sv
${FPNEW_HOME}/src/transdot_decomp_multiplier.sv
${FPNEW_HOME}/src/transdot_decomp_adder.sv
${FPNEW_HOME}/src/transdot_decomp_shifter.sv
${FPNEW_HOME}/src/transdot_decomp_exponent_datapath_fp8.sv
${FPNEW_HOME}/src/transdot_decomp_addend_datapath.sv
${FPNEW_HOME}/src/transdot_decomp_normalize_datapath.sv
${FPNEW_HOME}/src/transdot_fp4_dp.sv
${FPNEW_HOME}/src/transdot_fp4_fp8_fp16_fp32_fma.sv
#${FPNEW_HOME}/src/transdot_fp16_fp32_fma_simd.sv
//${FPNEW_HOME}/src/fpnew_fma_multi.sv
//${FPNEW_HOME}/src/fpnew_fma_multi_hier.sv
${FPNEW_HOME}/src/fpnew_noncomp.sv
${FPNEW_HOME}/src/fpnew_opgroup_block.sv
${FPNEW_HOME}/src/fpnew_opgroup_fmt_slice.sv
${FPNEW_HOME}/src/fpnew_opgroup_multifmt_slice.sv
${FPNEW_HOME}/src/fpnew_rounding.sv
${FPNEW_HOME}/src/fpnew_top.sv

${FPNEW_HOME}/src/common_cells/src/cf_math_pkg.sv
${FPNEW_HOME}/src/common_cells/src/ecc_pkg.sv
//${FPNEW_HOME}/src/common_cells/src/addr_decode.sv
//${FPNEW_HOME}/src/common_cells/src/binary_to_gray.sv
//${FPNEW_HOME}/src/common_cells/src/cb_filter_pkg.sv
//${FPNEW_HOME}/src/common_cells/src/cb_filter.sv
//${FPNEW_HOME}/src/common_cells/src/cdc_2phase.sv
//${FPNEW_HOME}/src/common_cells/src/cdc_fifo_2phase.sv
//${FPNEW_HOME}/src/common_cells/src/cdc_fifo_gray.sv
//${FPNEW_HOME}/src/common_cells/src/clk_div.sv
//${FPNEW_HOME}/src/common_cells/src/counter.sv
//${FPNEW_HOME}/src/common_cells/src/delta_counter.sv
//${FPNEW_HOME}/src/common_cells/src/ecc_decode.sv
//${FPNEW_HOME}/src/common_cells/src/ecc_encode.sv
//${FPNEW_HOME}/src/common_cells/src/edge_detect.sv
//${FPNEW_HOME}/src/common_cells/src/edge_propagator_rx.sv
//${FPNEW_HOME}/src/common_cells/src/edge_propagator_tx.sv
//${FPNEW_HOME}/src/common_cells/src/edge_propagator.sv
//${FPNEW_HOME}/src/common_cells/src/exp_backoff.sv
//${FPNEW_HOME}/src/common_cells/src/fall_through_register.sv
//${FPNEW_HOME}/src/common_cells/src/fifo_v3.sv
//${FPNEW_HOME}/src/common_cells/src/gray_to_binary.sv
//${FPNEW_HOME}/src/common_cells/src/id_queue.sv
//${FPNEW_HOME}/src/common_cells/src/isochronous_spill_register.sv
//${FPNEW_HOME}/src/common_cells/src/lfsr_8bit.sv
//${FPNEW_HOME}/src/common_cells/src/lfsr_16bit.sv
//${FPNEW_HOME}/src/common_cells/src/lfsr.sv
${FPNEW_HOME}/src/common_cells/src/lzc.sv
//${FPNEW_HOME}/src/common_cells/src/max_counter.sv
//${FPNEW_HOME}/src/common_cells/src/mv_filter.sv
//${FPNEW_HOME}/src/common_cells/src/onehot_to_bin.sv
//${FPNEW_HOME}/src/common_cells/src/plru_tree.sv
//${FPNEW_HOME}/src/common_cells/src/popcount.sv
${FPNEW_HOME}/src/common_cells/src/rr_arb_tree.sv
//${FPNEW_HOME}/src/common_cells/src/rstgen_bypass.sv
//${FPNEW_HOME}/src/common_cells/src/rstgen.sv
//${FPNEW_HOME}/src/common_cells/src/serial_deglitch.sv
//${FPNEW_HOME}/src/common_cells/src/shift_reg.sv
//${FPNEW_HOME}/src/common_cells/src/spill_register.sv
//${FPNEW_HOME}/src/common_cells/src/stream_arbiter_flushable.sv
//${FPNEW_HOME}/src/common_cells/src/stream_arbiter.sv
//${FPNEW_HOME}/src/common_cells/src/stream_delay.sv
//${FPNEW_HOME}/src/common_cells/src/stream_demux.sv
//${FPNEW_HOME}/src/common_cells/src/stream_fifo.sv
//${FPNEW_HOME}/src/common_cells/src/stream_filter.sv
//${FPNEW_HOME}/src/common_cells/src/stream_fork_dynamic.sv
//${FPNEW_HOME}/src/common_cells/src/stream_fork.sv
//${FPNEW_HOME}/src/common_cells/src/stream_intf.sv
//${FPNEW_HOME}/src/common_cells/src/stream_join.sv
//${FPNEW_HOME}/src/common_cells/src/stream_mux.sv
//${FPNEW_HOME}/src/common_cells/src/stream_omega_net.sv
//${FPNEW_HOME}/src/common_cells/src/stream_register.sv
//${FPNEW_HOME}/src/common_cells/src/stream_to_mem.sv
//${FPNEW_HOME}/src/common_cells/src/stream_xbar.sv
//${FPNEW_HOME}/src/common_cells/src/sub_per_hash.sv
//${FPNEW_HOME}/src/common_cells/src/sync_wedge.sv
//${FPNEW_HOME}/src/common_cells/src/sync.sv
//${FPNEW_HOME}/src/common_cells/src/unread.sv
//${FPNEW_HOME}/instances/fp32_addmul_no_simd.sv
//${FPNEW_HOME}/instances/fp16_addmul_no_simd.sv
//${FPNEW_HOME}/instances/fp32_fp16_addmul_no_simd.sv
//${FPNEW_HOME}/instances/fp8_addmul_no_simd.sv
//${FPNEW_HOME}/instances/int32_addmul_no_simd.sv
${FPNEW_HOME}/instances/transdot_fpu_top.sv

${FPNEW_HOME}/tb/sv_tb_new/tb_fpnew.sv
